In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import boxcox

In [2]:
file1 = pd.read_csv('file1.csv')
file2 = pd.read_csv('file2.csv')
file3 = pd.read_csv('file3.csv')

In [3]:
list(file1.columns)

['Customer',
 'ST',
 'GENDER',
 'Education',
 'Customer Lifetime Value',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Vehicle Class',
 'Total Claim Amount']

In [4]:
list(file2.columns)

['Customer',
 'ST',
 'GENDER',
 'Education',
 'Customer Lifetime Value',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Total Claim Amount',
 'Policy Type',
 'Vehicle Class']

In [5]:
list(file3.columns)

['Customer',
 'State',
 'Customer Lifetime Value',
 'Education',
 'Gender',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Total Claim Amount',
 'Vehicle Class']

In [6]:
def rename_columns(file3):
    file3.rename(columns={'State':'ST', 'Gender':'GENDER'}, inplace=True)
    return file3


file3=rename_columns(file3)

In [7]:
list(file3.columns)

['Customer',
 'ST',
 'Customer Lifetime Value',
 'Education',
 'GENDER',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Total Claim Amount',
 'Vehicle Class']

In [8]:
def merge_files():
    file1 = pd.read_csv('file1.csv')
    file2 = pd.read_csv('file2.csv')
    file3
    return pd.concat([file1,file2,file3], axis=0, ignore_index=True)

In [9]:
ca_df=merge_files()

In [10]:
ca_df

Customer          ST GENDER             Education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      Customer Lifetime Value   Income  Monthly Premium Auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      Number of Open Complaints     Policy Type  Vehicle Class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       Total Claim Amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [11]:
def lower_case_column_names(ca_df):
    ca_df.columns=[i.lower() for i in ca_df.columns]
    return ca_df

In [12]:
ca_df = lower_case_column_names(ca_df)

In [13]:
ca_df

customer          st gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [14]:
def drop_column(ca_df) :
    ca_df.drop(columns=["customer"], inplace=True)
    return ca_df

In [15]:
ca_df=drop_column(ca_df)

In [16]:
ca_df

st gender             education customer lifetime value  \
0      Washington    NaN                Master                     NaN   
1         Arizona      F              Bachelor              697953.59%   
2          Nevada      F              Bachelor             1288743.17%   
3      California      M              Bachelor              764586.18%   
4      Washington      M  High School or Below              536307.65%   
...           ...    ...                   ...                     ...   
12069  California      M              Bachelor             23405.98798   
12070  California      F               College             3096.511217   
12071  California      M              Bachelor             8163.890428   
12072  California      M               College             7524.442436   
12073  California      M               College             2611.836866   

        income  monthly premium auto number of open complaints  \
0          0.0                1000.0                    1/0/00   
1          0.0                  94.0                    1/0/00   
2      48767.0                 108.0                    1/0/00   
3          0.0                 106.0                    1/0/00   
4      36357.0                  68.0                    1/0/00   
...        ...                   ...                       ...   
12069  71941.0                  73.0                         0   
12070  21604.0                  79.0                         0   
12071      0.0                  85.0                         3   
12072  21941.0                  96.0                         0   
12073      0.0                  77.0                         0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[12074 rows x 10 columns]

In [17]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints     object
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [18]:
ca_df["number of open complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan, 0,
       2, 3, 1, 5, 4], dtype=object)

In [19]:
## Standardize the values in open complaints, taking only the middle value of 0/00/00
ca_df["number of open complaints"] = list(map(lambda x:int(x[2]) if isinstance(x, str) else x, ca_df["number of open complaints"]))



In [20]:
ca_df["number of open complaints"].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [21]:
## Standardize the values in customer lifetime value by getting rid of the % sign, first turn into string to identify tge values with "%""

ca_df['customer lifetime value'] = ca_df['customer lifetime value'].astype(str).str.replace('%', '')


In [22]:
ca_df["customer lifetime value"].head()

0           nan
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: customer lifetime value, dtype: object

In [23]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [24]:
ca_df['customer lifetime value']= pd.to_numeric(ca_df['customer lifetime value'], errors='coerce')


In [71]:
ca_df['customer lifetime value']

0        1.821960e+05
1        6.979536e+05
2        1.288743e+06
3        7.645862e+05
4        5.363077e+05
             ...     
12069    2.340599e+04
12070    3.096511e+03
12071    8.163890e+03
12072    7.524442e+03
12073    2.611837e+03
Name: customer lifetime value, Length: 12074, dtype: float64

In [26]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [27]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [28]:
ca_df['number of open complaints']=pd.to_numeric(ca_df['number of open complaints'], errors='coerce')


In [29]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [30]:
ca_df['gender'].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [31]:
ca_df['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [32]:
#Change the type of values in gender to string to 
ca_df['gender']= ca_df['gender'].astype(str)

In [33]:
ca_df['gender']=list(map(lambda x:'F' if ('emal' in x) else x, ca_df['gender']))

In [34]:
ca_df['gender']=list(map(lambda x:'M' if ('Male' in x) else x, ca_df['gender']))

In [35]:
ca_df['gender'].unique()

array(['nan', 'F', 'M'], dtype=object)

In [36]:
# Remove duplicates
ca_df.drop_duplicates()

st gender             education  customer lifetime value  \
0      Washington    nan                Master                      NaN   
1         Arizona      F              Bachelor             6.979536e+05   
2          Nevada      F              Bachelor             1.288743e+06   
3      California      M              Bachelor             7.645862e+05   
4      Washington      M  High School or Below             5.363077e+05   
...           ...    ...                   ...                      ...   
12069  California      M              Bachelor             2.340599e+04   
12070  California      F               College             3.096511e+03   
12071  California      M              Bachelor             8.163890e+03   
12072  California      M               College             7.524442e+03   
12073  California      M               College             2.611837e+03   

        income  monthly premium auto  number of open complaints  \
0          0.0                1000.0                        0.0   
1          0.0                  94.0                        0.0   
2      48767.0                 108.0                        0.0   
3          0.0                 106.0                        0.0   
4      36357.0                  68.0                        0.0   
...        ...                   ...                        ...   
12069  71941.0                  73.0                        0.0   
12070  21604.0                  79.0                        0.0   
12071      0.0                  85.0                        3.0   
12072  21941.0                  96.0                        0.0   
12073      0.0                  77.0                        0.0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[8880 rows x 10 columns]

In [37]:
#how to check if the deleted cells we actually duplicates?

In [38]:
#Replacing null values – 
#Replace missing values with means of the column (for numerical columns)

ca_df[ca_df['customer lifetime value'].isna()==True]

st gender             education  customer lifetime value  \
0     Washington    nan                Master                      NaN   
78    Washington      F                Master                      NaN   
988   Washington      M  High School or Below                      NaN   
1071         NaN    nan                   NaN                      NaN   
1072         NaN    nan                   NaN                      NaN   
...          ...    ...                   ...                      ...   
4007         NaN    nan                   NaN                      NaN   
4333  Washington      M  High School or Below                      NaN   
4380  Washington    nan  High School or Below                      NaN   
4588  Washington      M                Master                      NaN   
4869  Washington      F             Bachelors                      NaN   

       income  monthly premium auto  number of open complaints    policy type  \
0         0.0                1000.0                        0.0  Personal Auto   
78    41275.0                  96.0                        0.0  Personal Auto   
988   55561.0                  63.0                        0.0  Personal Auto   
1071      NaN                   NaN                        NaN            NaN   
1072      NaN                   NaN                        NaN            NaN   
...       ...                   ...                        ...            ...   
4007      NaN                   NaN                        NaN            NaN   
4333  51878.0                  66.0                        1.0  Personal Auto   
4380  36765.0                  66.0                        1.0  Personal Auto   
4588      0.0                  70.0                        0.0  Personal Auto   
4869  25859.0                  74.0                        0.0   Special Auto   

      vehicle class  total claim amount  
0     Four-Door Car            2.704934  
78    Four-Door Car           41.122303  
988   Four-Door Car          227.872071  
1071            NaN                 NaN  
1072            NaN                 NaN  
...             ...                 ...  
4007            NaN                 NaN  
4333  Four-Door Car          316.800000  
4380  Four-Door Car          320.849072  
4588  Four-Door Car          336.000000  
4869  Four-Door Car          355.200000  

[2944 rows x 10 columns]

In [39]:
### More than half of the values are null!!
### If it's necesary, those values can be replaced with the mean. A new

mean_value_clv = round(np.mean(ca_df['customer lifetime value']))

In [40]:
ca_df['customer lifetime value'] = ca_df['customer lifetime value'].fillna(mean_value_clv)

In [41]:
## income value
mean_income = round(np.mean(ca_df['income']))

In [42]:
ca_df['income'] = ca_df['income'].fillna(mean_income)

In [43]:
ca_df['income'].unique()

array([    0., 48767., 36357., ..., 66367., 71941., 21941.])

In [44]:
## monthly premium auto 
mean_monthly_premauto = round(np.mean(ca_df['monthly premium auto']))
ca_df['monthly premium auto'] = ca_df['monthly premium auto'].fillna(mean_monthly_premauto)

In [45]:
## number of open complaints 
mean_open_comp = round(np.mean(ca_df['number of open complaints']))
ca_df['number of open complaints'] = ca_df['number of open complaints'].fillna(mean_open_comp)

In [46]:
### total claim amount
mean_total_claim = round(np.mean(ca_df['total claim amount']))
ca_df['total claim amount'] = ca_df['total claim amount'].fillna(mean_total_claim)

In [47]:
ca_df['monthly premium auto'].unique()

array([ 1000.,    94.,   108.,   106.,    68.,    69.,    67.,   101.,
          71.,    93.,   110.,    70.,    64.,    72.,    74.,    79.,
          73.,    61.,   111.,    80.,    63.,   237.,    65.,   130.,
          62.,   117.,    91.,    90.,    66.,    99.,   103., 35354.,
         172.,    92.,   104.,   113.,   124.,   105.,   100.,   112.,
          97.,    95.,   102.,    96.,   186.,    77.,    76.,   119.,
          87.,   109.,   107.,    88.,    85.,  6464.,   133.,    86.,
          78.,    89.,   192.,   118.,   140.,   127.,   126.,    82.,
         115.,   217.,   114.,   138.,    81.,   255.,   150.,   123.,
         116.,   190.,    98.,   159.,    84.,    83.,   152.,   136.,
         245.,   135.,  1005.,   225.,   132.,   153.,   121.,   139.,
         154.,   161.,   156.,   171.,   244.,   183.,   176.,   230.,
         129.,   177.,   181.,   196.,   131.,   276.,   253.,   137.,
         180.,   203.,   147.,   165.,   198.,   125.,   193.,   128.,
      

In [48]:
ca_df['total claim amount'].unique()

array([   2.704934, 1131.464935,  566.472247, ...,  541.282007,
        198.234764,  790.784983])

In [49]:
ca_df['number of open complaints'].unique()

array([0., 2., 1., 3., 5., 4.])

In [50]:
ca_df["st"] = ca_df["st"].astype("str")

In [51]:
ca_df["st"]

0        Washington
1           Arizona
2            Nevada
3        California
4        Washington
            ...    
12069    California
12070    California
12071    California
12072    California
12073    California
Name: st, Length: 12074, dtype: object

In [52]:
ca_df['st'] = list(map(lambda x: 'Arizona' if ('AZ' in x) else x, ca_df['st']))

In [53]:
ca_df['st'] = list(map(lambda x: 'California' if ('Cali' in x) else x, ca_df['st']))

In [54]:
ca_df['st'] = list(map(lambda x: 'Washington' if ('WA' in x) else x, ca_df['st']))

In [55]:
ca_df["st"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'nan'],
      dtype=object)

In [56]:
ca_df["st"] = ca_df["st"].astype("category")

In [57]:
state_region_labels = {'California':'West', 'Oregon':'Nord West', 'Washington':'East','Nevada':'Central', 'Arizona':'Central'}

In [58]:
ca_df['st'].replace(state_region_labels, inplace = True)

In [59]:
ca_df['st'].unique()

array(['East', 'Central', 'West', 'Nord West', 'nan'], dtype=object)

In [60]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [61]:
ca_df['st'] = ca_df['st'].str.lower()
ca_df['st']

0           east
1        central
2        central
3           west
4           east
          ...   
12069       west
12070       west
12071       west
12072       west
12073       west
Name: st, Length: 12074, dtype: object

In [62]:
ca_df['gender'] = ca_df['gender'].str.lower()
ca_df['gender']

0        nan
1          f
2          f
3          m
4          m
        ... 
12069      m
12070      f
12071      m
12072      m
12073      m
Name: gender, Length: 12074, dtype: object

In [63]:
ca_df['education'] = ca_df['education'].str.lower()
ca_df['education']

0                      master
1                    bachelor
2                    bachelor
3                    bachelor
4        high school or below
                 ...         
12069                bachelor
12070                 college
12071                bachelor
12072                 college
12073                 college
Name: education, Length: 12074, dtype: object

In [64]:
ca_df['policy type'] = ca_df['policy type'].str.lower()

In [65]:
ca_df['policy type']

0         personal auto
1         personal auto
2         personal auto
3        corporate auto
4         personal auto
              ...      
12069     personal auto
12070    corporate auto
12071    corporate auto
12072     personal auto
12073    corporate auto
Name: policy type, Length: 12074, dtype: object

In [66]:
ca_df['vehicle class'] = ca_df['vehicle class'].str.lower()

In [67]:
ca_df['vehicle class']

0        four-door car
1        four-door car
2         two-door car
3                  suv
4        four-door car
             ...      
12069    four-door car
12070    four-door car
12071    four-door car
12072    four-door car
12073     two-door car
Name: vehicle class, Length: 12074, dtype: object

In [68]:
ca_df.head()

st gender             education  customer lifetime value   income  \
0     east    nan                master                182196.00      0.0   
1  central      f              bachelor                697953.59      0.0   
2  central      f              bachelor               1288743.17  48767.0   
3     west      m              bachelor                764586.18      0.0   
4     east      m  high school or below                536307.65  36357.0   

   monthly premium auto  number of open complaints     policy type  \
0                1000.0                        0.0   personal auto   
1                  94.0                        0.0   personal auto   
2                 108.0                        0.0   personal auto   
3                 106.0                        0.0  corporate auto   
4                  68.0                        0.0   personal auto   

   vehicle class  total claim amount  
0  four-door car            2.704934  
1  four-door car         1131.464935  
2   two-door car          566.472247  
3            suv          529.881344  
4  four-door car           17.269323

In [69]:
ca_df_objects = ca_df.select_dtypes(include=['object'], exclude=['float64'])
ca_df_objects

st gender             education     policy type  vehicle class
0         east    nan                master   personal auto  four-door car
1      central      f              bachelor   personal auto  four-door car
2      central      f              bachelor   personal auto   two-door car
3         west      m              bachelor  corporate auto            suv
4         east      m  high school or below   personal auto  four-door car
...        ...    ...                   ...             ...            ...
12069     west      m              bachelor   personal auto  four-door car
12070     west      f               college  corporate auto  four-door car
12071     west      m              bachelor  corporate auto  four-door car
12072     west      m               college   personal auto  four-door car
12073     west      m               college  corporate auto   two-door car

[12074 rows x 5 columns]

In [70]:
ca_df_numerical = ca_df.select_dtypes(include=['float64'], exclude=['object'])
ca_df_numerical

customer lifetime value   income  monthly premium auto  \
0                 1.821960e+05      0.0                1000.0   
1                 6.979536e+05      0.0                  94.0   
2                 1.288743e+06  48767.0                 108.0   
3                 7.645862e+05      0.0                 106.0   
4                 5.363077e+05  36357.0                  68.0   
...                        ...      ...                   ...   
12069             2.340599e+04  71941.0                  73.0   
12070             3.096511e+03  21604.0                  79.0   
12071             8.163890e+03      0.0                  85.0   
12072             7.524442e+03  21941.0                  96.0   
12073             2.611837e+03      0.0                  77.0   

       number of open complaints  total claim amount  
0                            0.0            2.704934  
1                            0.0         1131.464935  
2                            0.0          566.472247  
3                            0.0          529.881344  
4                            0.0           17.269323  
...                          ...                 ...  
12069                        0.0          198.234764  
12070                        0.0          379.200000  
12071                        3.0          790.784983  
12072                        0.0          691.200000  
12073                        0.0          369.600000  

[12074 rows x 5 columns]

In [76]:
ca_df.isna().sum()

st                              0
gender                          0
education                    2937
customer lifetime value         0
income                          0
monthly premium auto            0
number of open complaints       0
policy type                  2937
vehicle class                2937
total claim amount              0
dtype: int64